name: Android CD
on:
  workflow_dispatch:
    inputs:
      buildType:
        description: "생성할 Build Type 설정"
        required: true
        default: 'release'
        type: choice
        options:
          - debug
          - release
  push:
    branches: [ main ]

jobs:
  build:
    name: Beep CD
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - name: set up JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: 17

      - name: Create Keystore
        run: |
          echo '${{ secrets.KEYSTORE_PROPERTIES }}' > ./keystore.properties
          echo '${{ secrets.RELEASE_KEYSTORE_JKS }}' | base64 -d > ./beep-release.jks

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Run On Build
        run: |
          if [ ${{ github.event.inputs.buildType }} == 'debug' ]; then
            echo 'Build Debug'
            ./gradlew -Psplit clean -w assembleDebug
            mv app/build/outputs/apk/debug/app-debug.apk beep.apk
          else
            echo 'Build Release'
            ./gradlew -Psplit clean -w assembleRelease
            mv app/build/outputs/apk/release/app-release.apk beep.apk
          fi

      - name: Firebase App Distribution
        uses: wzieba/Firebase-Distribution-Github-Action@v1
        with:
          appId: ${{secrets.FIREBASE_APP_ID}}
          serviceCredentialsFileContent: ${{ secrets.CREDENTIAL_FILE_CONTENT }}
          groups: team
          file: beep.apk

      - name: Slack Notification
        uses: 8398a7/action-slack@v3
        with:
          status: ${{ job.status }}
          author_name: 안드로이드 Release
          fields: repo, commit ,message, author, took
          mention: audxo112
          if_mention: failure, cancelled
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL_DEPLOY }}
        if: always()
