name: Deploy Debug
on: workflow_dispatch
jobs:
  build:
    name: Beep CD
    runs-on: ubuntu-latest

    env:
      BUILD_TYPE: "Debug"

    steps:
      - uses: actions/checkout@v3

      - name: set up JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: 17

      - name: Create Keystore
        run: |
          echo '${{ secrets.KEYSTORE_PROPERTIES }}' > ./keystore.properties
          echo '${{ secrets.KEYSTORE_DEBUG_JKS }}' | base64 -d > ./beep-debug.jks

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Run On Build
        run: |
          ./gradlew -Psplit clean -w assemble${{BUILD_TYPE}}
          mv app/build/outputs/apk/${{BUILD_TYPE}}/app-${{BUILD_TYPE}}.apk beep-${{BUILD_TYPE}}.apk

      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: ${{BUILD_TYPE}}
          path: ./beep-${{BUILD_TYPE}}.apk

      - name: Firebase App Distribution
        uses: wzieba/Firebase-Distribution-Github-Action@v1
        with:
          appId: ${{secrets.FIREBASE_APP_ID}}
          serviceCredentialsFileContent: ${{ secrets.CREDENTIAL_FILE_CONTENT }}
          groups: team
          file: beep-${{BUILD_TYPE}}.apk

      - name: Slack Notification
        uses: 8398a7/action-slack@v3
        with:
          status: ${{ job.status }}
          author_name: 안드로이드 ${{BUILD_TYPE}}
          fields: repo, commit ,message, author, took
          mention: audxo112
          if_mention: failure, cancelled
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL_DEPLOY }}
        if: always()
