name: Android CD
on:
  workflow_dispatch:
    inputs:
      build-type:
        description: "생성할 Build Type 설정"
        required: true
        default: 'Release'
        type: choice
        options:
          - Debug
          - Release
  push:
    branches: [ main ]

jobs:
  build:
    name: Beep CD
    runs-on: ubuntu-latest

    env:
      DEBUG: "Debug"
      RELEASE: "Release"
      BUILD_TYPE: ${{ inputs.build-type != '' && inputs.build-type || 'Release' }}

    steps:
      - name: Check Build Type
        run: |
          echo ${{env.BUILD_TYPE}}
          if [ contains(fromJson('[${{env.DEBUG}}, ${{env.RELEASE}}]'), ${{ env.BUILD_TYPE }})]; then
            echo '${{ secrets.KEYSTORE_PROPERTIES }}' > ./keystore.properties  
          else
            exit 1
          fi

      - uses: actions/checkout@v3

      - name: set up JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: 17

      - name: Create Keystore
        run: |
          if [ ${{ env.BUILD_TYPE }} == ${{env.DEBUG}} ]; then
            echo '${{ secrets.KEYSTORE_DEBUG_JKS }}' | base64 -d > ./beep-debug.jks
          elif [ ${{ env.BUILD_TYPE }} == ${{env.RELEASE}} ]; then
            echo '${{ secrets.KEYSTORE_RELEASE_JKS }}' | base64 -d > ./beep-release.jks
          fi

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Run On Build
        run: |
          ./gradlew -Psplit clean -w assemble${{ env.BUILD_TYPE }}
          mv app/build/outputs/apk/${{ env.BUILD_TYPE }}/app-${{ env.BUILD_TYPE }}.apk beep.apk

#      - name: Firebase App Distribution
#        uses: wzieba/Firebase-Distribution-Github-Action@v1
#        with:
#          appId: ${{secrets.FIREBASE_APP_ID}}
#          serviceCredentialsFileContent: ${{ secrets.CREDENTIAL_FILE_CONTENT }}
#          groups: team
#          file: beep.apk

      - name: Slack Notification
        uses: 8398a7/action-slack@v3
        with:
          status: ${{ job.status }}
          author_name: 안드로이드 ${{ env.BUILD_TYPE }}
          fields: repo, commit ,message, author, took
          mention: audxo112
          if_mention: failure, cancelled
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL_DEPLOY }}
        if: always()
